using Lanilor.LootBoxes.Mod;
using System.Collections.Generic;
using JetBrains.Annotations;

namespace Lanilor.LootBoxes.Things
{
    [UsedImplicitly]
    public class CompUseEffectLootBoxGoldSmall : CompUseEffectLootBox
    {
        protected override LootBoxType LootBoxType => LootBoxType.GoldS;
        protected override int SetMinimum => ModLootBoxes.Settings?.SetMinGoldS ?? 1;
        protected override int SetMaximum => ModLootBoxes.Settings?.SetMaxGoldS ?? 4;
        protected override float MaximumMarketRewardValue => ModLootBoxes.Settings?.GoldSRewardValue ?? 650;

        protected override IEnumerable<LootboxReward> RewardTable => new List<LootboxReward>
        {
            new LootboxReward(9, new Reward("MealSurvivalPack", 4, 8, 20)),
            new LootboxReward(9, new Reward("MealNutrientPaste", 3, 10, 50)),
            new LootboxReward(9, new Reward("MealSimple", 4, 10, 30)),
            new LootboxReward(9, new Reward("MealFine", 4, 8, 20)),
            new LootboxReward(9, new Reward("MealLavish", 3, 7, 15)),
            new LootboxReward(9, new Reward("Kibble", 20, 50, 100)),
            new LootboxReward(9, new Reward("Chocolate", 4, 8, 20)),
            new LootboxReward(9, new Reward("InsectJelly", 5, 20, 75)),
            new LootboxReward(10, new Reward("Beer", 5, 10, 25)),
            new LootboxReward(10, new Reward("SmokeleafJoint", 3, 6, 20)),
            new LootboxReward(6, new Reward("GoJuice", 1, 3, 7)),
            new LootboxReward(3, new Reward("Luciferium", 1, 2, 5)),
            new LootboxReward(7, new Reward("Penoxycyline", 2, 5, 15)),
            new LootboxReward(9, new Reward("Yayo", 2, 5, 15)),
            new LootboxReward(8, new Reward("WakeUp", 2, 3, 10)),
            new LootboxReward(5, new Reward("Beer", 5, 10, 30), new Reward("SmokeleafJoint", 3, 8, 25),
                new Reward("Yayo", 2, 5, 15)),
            new LootboxReward(3, new Reward("SmokeleafJoint", 4, 10, 10), new Reward("GoJuice", 2, 4, 4),
                new Reward("Luciferium", 1, 2, 2), new Reward("Yayo", 3, 8, 8), new Reward("WakeUp", 2, 5, 5)),
            new LootboxReward(3, new Reward("BionicEye")),
            new LootboxReward(3, new Reward("BionicArm")),
            new LootboxReward(3, new Reward("BionicLeg")),
            new LootboxReward(3, new Reward("BionicSpine")),
            new LootboxReward(3, new Reward("BionicHeart")),
            new LootboxReward(3, new Reward("BionicStomach")),
            new LootboxReward(3, new Reward("BionicEar")),
            new LootboxReward(1, new Reward("ArchotechEye")),
            new LootboxReward(1, new Reward("ArchotechArm")),
            new LootboxReward(1, new Reward("ArchotechLeg")),
            new LootboxReward(2, new Reward("Joywire")),
            new LootboxReward(2, new Reward("Painstopper")),
            new LootboxReward(7, new Reward("MedicineIndustrial", 1, 5, 10)),
            new LootboxReward(4, new Reward("MedicineUltratech", 1, 2, 5)),
            new LootboxReward(9, new Reward("ComponentIndustrial", 1, 2, 8)),
            new LootboxReward(2, new Reward("ComponentSpacer")),
            new LootboxReward(8, new Reward("Neutroamine", 3, 10, 25)),
            new LootboxReward(10, new Reward("Chemfuel", 10, 25, 150)),
            new LootboxReward(8, new Reward("Shell_HighExplosive", 1, 3, 10)),
            new LootboxReward(7, new Reward("Shell_Incendiary", 1, 3, 10)),
            new LootboxReward(5, new Reward("Shell_EMP", 1, 2, 5)),
            new LootboxReward(7, new Reward("Shell_Firefoam", 1, 2, 5)),
            new LootboxReward(3, new Reward("Shell_AntigrainWarhead")),
            new LootboxReward(2, new Reward("Shell_HighExplosive", 2, 5, 5), new Reward("Shell_Incendiary", 2, 5, 5),
                new Reward("Shell_EMP"), new Reward("Shell_AntigrainWarhead")),
            new LootboxReward(2, new Reward("ThrumboHorn")),
            new LootboxReward(4, new Reward("ElephantTusk", 1, 1, 3)),
            new LootboxReward(9, new Reward("Silver", 20, 50, 300)),
            new LootboxReward(8, new Reward("Gold", 2, 5, 15)),
            new LootboxReward(10, new Reward("Steel", 10, 30, 150)),
            new LootboxReward(8, new Reward("Plasteel", 5, 15, 60)),
            new LootboxReward(10, new Reward("WoodLog", 10, 40, 380)),
            new LootboxReward(5, new Reward("Uranium", 3, 8, 25)),
            new LootboxReward(8, new Reward("Jade", 5, 10, 50)),
            new LootboxReward(10, new Reward("Cloth", 20, 40, 150)),
            new LootboxReward(9, new Reward("Synthread", 10, 20, 80)),
            new LootboxReward(8, new Reward("DevilstrandCloth", 5, 12, 45)),
            new LootboxReward(7, new Reward("Hyperweave", 4, 7, 25)),
            new LootboxReward(8, new Reward("Leather_Elephant", 10, 20, 80)),
            new LootboxReward(8, new Reward("Leather_Heavy", 10, 20, 80)),
            new LootboxReward(7, new Reward("Leather_Rhinoceros", 10, 20, 80)),
            new LootboxReward(7, new Reward("Leather_Thrumbo", 10, 20, 80)),
            new LootboxReward(3, new Reward("MechSerumHealer", 1, 2, 3)),
            new LootboxReward(1, new Reward("MechSerumResurrector")),
            new LootboxReward(3, new Reward("PsychicAnimalPulser", 1, 1, 2)),
            new LootboxReward(3, new Reward("PsychicSoothePulser", 1, 1, 2)),
#if V10 || V11
            new LootboxReward(3, new Reward("PsychicInsanityLance", 1, 1, 2)),
            new LootboxReward(3, new Reward("PsychicShockLance", 1, 1, 2)),
            new LootboxReward(1, new Reward("PsychicInsanityLance"), new Reward("PsychicShockLance"),
                new Reward("PsychicAnimalPulser"), new Reward("PsychicSoothePulser")),
#else
            new LootboxReward(3, new Reward("Apparel_PsychicInsanityLance", 1, 1, 2)),
            new LootboxReward(3, new Reward("Apparel_PsychicShockLance", 1, 1, 2)),
            new LootboxReward(1, new Reward("Apparel_PsychicInsanityLance"), new Reward("Apparel_PsychicShockLance"),
                new Reward("PsychicAnimalPulser"), new Reward("PsychicSoothePulser")),
#endif
            new LootboxReward(6, new Reward("Gun_Revolver", 1, 1, 5)),
            new LootboxReward(6, new Reward("Gun_Autopistol", 1, 1, 4)),
            new LootboxReward(5, new Reward("Gun_MachinePistol", 1, 1, 3)),
            new LootboxReward(4, new Reward("Gun_IncendiaryLauncher", 1, 1, 2)),
            new LootboxReward(5, new Reward("Gun_BoltActionRifle", 1, 1, 3)),
            new LootboxReward(5, new Reward("Gun_PumpShotgun", 1, 1, 3)),
            new LootboxReward(3, new Reward("Gun_ChainShotgun", 1, 1, 3)),
            new LootboxReward(3, new Reward("Gun_HeavySMG", 1, 1, 3)),
            new LootboxReward(3, new Reward("Gun_LMG", 1, 1, 2)),
            new LootboxReward(3, new Reward("Gun_AssaultRifle", 1, 1, 2)),
            new LootboxReward(3, new Reward("Gun_SniperRifle", 1, 1, 2)),
            new LootboxReward(2, new Reward("Gun_Minigun")),
            new LootboxReward(2, new Reward("Gun_ChargeRifle")),
            new LootboxReward(2, new Reward("Gun_ChargeLance")),
            new LootboxReward(3, new Reward("Weapon_GrenadeFrag", 1, 1, 2)),
            new LootboxReward(3, new Reward("Weapon_GrenadeMolotov", 1, 1, 2)),
            new LootboxReward(3, new Reward("Weapon_GrenadeEMP", 1, 1, 2)),
            new LootboxReward(1, new Reward("Gun_TripleRocket")),
            new LootboxReward(1, new Reward("Gun_DoomsdayRocket")),
            new LootboxReward(1, new Reward("OrbitalTargeterBombardment")),
            new LootboxReward(1, new Reward("OrbitalTargeterPowerBeam")),
            new LootboxReward(3, new Reward("Apparel_ShieldBelt", 1, 1, 2)),
            new LootboxReward(6, new Reward("Apparel_SmokepopBelt", 1, 1, 3)),
            new LootboxReward(6, new Reward("Apparel_CowboyHat", 1, 3, 7)),
            new LootboxReward(6, new Reward("Apparel_BowlerHat", 1, 3, 7)),
            new LootboxReward(6, new Reward("Apparel_Tuque", 1, 3, 7)),
            new LootboxReward(6, new Reward("Apparel_SimpleHelmet", 1, 3, 7)),
            new LootboxReward(4, new Reward("Apparel_AdvancedHelmet", 1, 2, 3)),
            new LootboxReward(1, new Reward("Apparel_PowerArmorHelmet")),
            new LootboxReward(6, new Reward("Apparel_Parka", 1, 2, 3)),
            new LootboxReward(6, new Reward("Apparel_Pants", 1, 2, 3)),
            new LootboxReward(6, new Reward("Apparel_BasicShirt", 1, 2, 3)),
            new LootboxReward(6, new Reward("Apparel_CollarShirt", 1, 2, 3)),
            new LootboxReward(6, new Reward("Apparel_Duster", 1, 2, 3)),
            new LootboxReward(5, new Reward("Apparel_FlakVest", 1, 1, 3)),
            new LootboxReward(5, new Reward("Apparel_FlakPants", 1, 1, 3)),
            new LootboxReward(5, new Reward("Apparel_FlakJacket", 1, 1, 3)),
            new LootboxReward(1, new Reward("Apparel_PowerArmor")),
            new LootboxReward(5, new Reward("Apparel_Tuque"), new Reward("Apparel_Parka"),
                new Reward("Apparel_Pants"), new Reward("Apparel_CollarShirt")),
            new LootboxReward(5, new Reward("Apparel_BowlerHat"), new Reward("Apparel_Duster"),
                new Reward("Apparel_Pants"), new Reward("Apparel_CollarShirt")),
            new LootboxReward(2, new Reward("Apparel_AdvancedHelmet"), new Reward("Apparel_FlakVest"),
                new Reward("Apparel_FlakPants"), new Reward("Apparel_FlakJacket")),
            new LootboxReward(1, new Reward("Apparel_PowerArmorHelmet"),
                new Reward("Apparel_PowerArmor")),
            new LootboxReward(2, new Reward("LootBoxTreasure")),
            new LootboxReward(3, new Reward("LootBoxSilverSmall")),
            new LootboxReward(1, new Reward("LootBoxSilverLarge")),
            new LootboxReward(1, new Reward("LootBoxGoldSmall")),
            new LootboxReward(1, new Reward("LootBoxPandora"))
        };
    }
}