using Lanilor.LootBoxes.Mod;
using System.Collections.Generic;

namespace Lanilor.LootBoxes.Things
{
    public class CompUseEffectLootBoxGoldLarge : CompUseEffectLootBox
    {
        protected override LootBoxType LootBoxType => LootBoxType.GoldL;
        protected override int SetMinimum => ModLootBoxes.Settings?.SetMinGoldL ?? 3;
        protected override int SetMaximum => ModLootBoxes.Settings?.SetMaxGoldL ?? 9;
        protected override float MaximumMarketRewardValue => ModLootBoxes.Settings?.GoldLRewardValue ?? 1000;

        protected override IEnumerable<LootboxReward> RewardTable => new List<LootboxReward>
        {
            new LootboxReward(8, new Reward("MealSurvivalPack", 5, 10, 30)),
            new LootboxReward(8, new Reward("MealNutrientPaste", 5, 20, 100)),
            new LootboxReward(8, new Reward("MealSimple", 5, 15, 50)),
            new LootboxReward(8, new Reward("MealFine", 5, 10, 30)),
            new LootboxReward(8, new Reward("MealLavish", 5, 10, 25)),
            new LootboxReward(8, new Reward("Kibble", 20, 100, 400)),
            new LootboxReward(8, new Reward("Chocolate", 5, 10, 50)),
            new LootboxReward(8, new Reward("InsectJelly", 10, 50, 150)),
            new LootboxReward(9, new Reward("Beer", 5, 15, 50)),
            new LootboxReward(9, new Reward("SmokeleafJoint", 4, 10, 30)),
            new LootboxReward(6, new Reward("GoJuice", 2, 5, 10)),
            new LootboxReward(3, new Reward("Luciferium", 1, 3, 10)),
            new LootboxReward(6, new Reward("Penoxycyline", 3, 7, 25)),
            new LootboxReward(8, new Reward("Yayo", 3, 7, 25)),
            new LootboxReward(7, new Reward("WakeUp", 2, 5, 15)),
            new LootboxReward(5, new Reward("Beer", 5, 15, 50), new Reward("SmokeleafJoint", 4, 10, 30),
                new Reward("Yayo", 3, 7, 25)),
            new LootboxReward(3, new Reward("SmokeleafJoint", 4, 15, 15), new Reward("GoJuice", 2, 5, 5),
                new Reward("Luciferium", 1, 3, 3), new Reward("Yayo", 3, 10, 10), new Reward("WakeUp", 2, 8, 8)),
            new LootboxReward(3, new Reward("BionicEye", 1, 1, 2)),
            new LootboxReward(3, new Reward("BionicArm", 1, 1, 2)),
            new LootboxReward(3, new Reward("BionicLeg", 1, 1, 2)),
            new LootboxReward(3, new Reward("BionicSpine", 1, 1, 2)),
            new LootboxReward(3, new Reward("BionicHeart", 1, 1, 2)),
            new LootboxReward(3, new Reward("BionicStomach", 1, 1, 2)),
            new LootboxReward(3, new Reward("BionicEar", 1, 1, 2)),
            new LootboxReward(1, new Reward("ArchotechEye")),
            new LootboxReward(1, new Reward("ArchotechArm")),
            new LootboxReward(1, new Reward("ArchotechLeg")),
            new LootboxReward(2, new Reward("Joywire", 1, 1, 2)),
            new LootboxReward(2, new Reward("Painstopper", 1, 1, 2)),
            new LootboxReward(6, new Reward("MedicineIndustrial", 2, 6, 15)),
            new LootboxReward(4, new Reward("MedicineUltratech", 2, 4, 9)),
            new LootboxReward(8, new Reward("ComponentIndustrial", 1, 3, 13)),
            new LootboxReward(2, new Reward("ComponentSpacer", 1, 1, 3)),
            new LootboxReward(8, new Reward("Neutroamine", 5, 15, 50)),
            new LootboxReward(9, new Reward("Chemfuel", 20, 50, 225)),
            new LootboxReward(7, new Reward("Shell_HighExplosive", 2, 4, 15)),
            new LootboxReward(6, new Reward("Shell_Incendiary", 2, 4, 15)),
            new LootboxReward(5, new Reward("Shell_EMP", 1, 3, 10)),
            new LootboxReward(6, new Reward("Shell_Firefoam", 2, 4, 10)),
            new LootboxReward(3, new Reward("Shell_AntigrainWarhead", 1, 1, 4)),
            new LootboxReward(3, new Reward("Shell_HighExplosive", 2, 10, 10),
                new Reward("Shell_Incendiary", 2, 10, 10), new Reward("Shell_EMP"),
                new Reward("Shell_AntigrainWarhead")),
            new LootboxReward(3, new Reward("ThrumboHorn", 1, 1, 2)),
            new LootboxReward(5, new Reward("ElephantTusk", 1, 1, 5)),
            new LootboxReward(9, new Reward("Silver", 50, 90, 900)),
            new LootboxReward(8, new Reward("Gold", 5, 15, 50)),
            new LootboxReward(10, new Reward("Steel", 10, 40, 380)),
            new LootboxReward(8, new Reward("Plasteel", 5, 20, 75)),
            new LootboxReward(9, new Reward("WoodLog", 10, 40, 380)),
            new LootboxReward(5, new Reward("Uranium", 4, 10, 30)),
            new LootboxReward(8, new Reward("Jade", 25, 50, 200)),
            new LootboxReward(9, new Reward("Cloth", 20, 50, 225)),
            new LootboxReward(8, new Reward("Synthread", 10, 25, 100)),
            new LootboxReward(8, new Reward("DevilstrandCloth", 5, 15, 50)),
            new LootboxReward(7, new Reward("Hyperweave", 4, 8, 30)),
            new LootboxReward(8, new Reward("Leather_Elephant", 10, 25, 100)),
            new LootboxReward(8, new Reward("Leather_Heavy", 10, 25, 100)),
            new LootboxReward(7, new Reward("Leather_Rhinoceros", 10, 25, 100)),
            new LootboxReward(7, new Reward("Leather_Thrumbo", 10, 25, 100)),
            new LootboxReward(3, new Reward("MechSerumHealer", 1, 2, 4)),
            new LootboxReward(1, new Reward("MechSerumResurrector")),
            new LootboxReward(3, new Reward("PsychicAnimalPulser", 1, 1, 2)),
            new LootboxReward(3, new Reward("PsychicSoothePulser", 1, 1, 2)),
#if V12
            new LootboxReward(3, new Reward("Apparel_PsychicInsanityLance", 1, 1, 2)),
            new LootboxReward(3, new Reward("Apparel_PsychicShockLance", 1, 1, 2)),
            new LootboxReward(2, new Reward("Apparel_PsychicInsanityLance"), new Reward("Apparel_PsychicShockLance"),
                new Reward("PsychicAnimalPulser"), new Reward("PsychicSoothePulser")),
#else
            new LootboxReward(3, new Reward("PsychicInsanityLance", 1, 1, 2)),
            new LootboxReward(3, new Reward("PsychicShockLance", 1, 1, 2)),
            new LootboxReward(2, new Reward("PsychicInsanityLance"), new Reward("PsychicShockLance"),
                new Reward("PsychicAnimalPulser"), new Reward("PsychicSoothePulser")),
#endif
            new LootboxReward(5, new Reward("Gun_Revolver", 1, 1, 8)),
            new LootboxReward(5, new Reward("Gun_Autopistol", 1, 1, 7)),
            new LootboxReward(4, new Reward("Gun_MachinePistol", 1, 1, 5)),
            new LootboxReward(4, new Reward("Gun_IncendiaryLauncher", 1, 1, 3)),
            new LootboxReward(4, new Reward("Gun_BoltActionRifle", 1, 1, 5)),
            new LootboxReward(4, new Reward("Gun_PumpShotgun", 1, 1, 5)),
            new LootboxReward(3, new Reward("Gun_ChainShotgun", 1, 1, 3)),
            new LootboxReward(3, new Reward("Gun_HeavySMG", 1, 1, 3)),
            new LootboxReward(3, new Reward("Gun_LMG", 1, 1, 2)),
            new LootboxReward(3, new Reward("Gun_AssaultRifle", 1, 1, 2)),
            new LootboxReward(3, new Reward("Gun_SniperRifle", 1, 1, 2)),
            new LootboxReward(2, new Reward("Gun_Minigun", 1, 1, 2)),
            new LootboxReward(2, new Reward("Gun_ChargeRifle", 1, 1, 2)),
            new LootboxReward(2, new Reward("Gun_ChargeLance", 1, 1, 2)),
            new LootboxReward(3, new Reward("Weapon_GrenadeFrag", 1, 1, 3)),
            new LootboxReward(3, new Reward("Weapon_GrenadeMolotov", 1, 1, 3)),
            new LootboxReward(3, new Reward("Weapon_GrenadeEMP", 1, 1, 3)),
            new LootboxReward(1, new Reward("Gun_TripleRocket")),
            new LootboxReward(1, new Reward("Gun_DoomsdayRocket")),
            new LootboxReward(1, new Reward("OrbitalTargeterBombardment")),
            new LootboxReward(1, new Reward("OrbitalTargeterPowerBeam")),
            new LootboxReward(3, new Reward("Apparel_ShieldBelt", 1, 1, 3)),
            new LootboxReward(5, new Reward("Apparel_SmokepopBelt", 1, 1, 5)),
            new LootboxReward(5, new Reward("Apparel_CowboyHat", 2, 3, 12)),
            new LootboxReward(5, new Reward("Apparel_BowlerHat", 2, 3, 12)),
            new LootboxReward(5, new Reward("Apparel_Tuque", 2, 3, 12)),
            new LootboxReward(5, new Reward("Apparel_SimpleHelmet", 2, 3, 12)),
            new LootboxReward(4, new Reward("Apparel_AdvancedHelmet", 1, 2, 5)),
            new LootboxReward(1, new Reward("Apparel_PowerArmorHelmet")),
            new LootboxReward(5, new Reward("Apparel_Parka", 1, 2, 5)),
            new LootboxReward(5, new Reward("Apparel_Pants", 1, 2, 5)),
            new LootboxReward(5, new Reward("Apparel_BasicShirt", 1, 2, 5)),
            new LootboxReward(5, new Reward("Apparel_CollarShirt", 1, 2, 5)),
            new LootboxReward(5, new Reward("Apparel_Duster", 1, 2, 5)),
            new LootboxReward(4, new Reward("Apparel_FlakVest", 1, 1, 5)),
            new LootboxReward(4, new Reward("Apparel_FlakPants", 1, 1, 5)),
            new LootboxReward(4, new Reward("Apparel_FlakJacket", 1, 1, 5)),
            new LootboxReward(1, new Reward("Apparel_PowerArmor")),
            new LootboxReward(5, new Reward("Apparel_Tuque"), new Reward("Apparel_Parka"),
                new Reward("Apparel_Pants"), new Reward("Apparel_CollarShirt")),
            new LootboxReward(5, new Reward("Apparel_BowlerHat"), new Reward("Apparel_Duster"),
                new Reward("Apparel_Pants"), new Reward("Apparel_CollarShirt")),
            new LootboxReward(3, new Reward("Apparel_AdvancedHelmet"), new Reward("Apparel_FlakVest"),
                new Reward("Apparel_FlakPants"), new Reward("Apparel_FlakJacket")),
            new LootboxReward(1, new Reward("Apparel_PowerArmorHelmet"),
                new Reward("Apparel_PowerArmor")),
            new LootboxReward(3, new Reward("LootBoxTreasure")),
            new LootboxReward(4, new Reward("LootBoxSilverSmall")),
            new LootboxReward(2, new Reward("LootBoxSilverLarge")),
            new LootboxReward(1, new Reward("LootBoxGoldSmall")),
            new LootboxReward(1, new Reward("LootBoxGoldLarge")),
            new LootboxReward(1, new Reward("LootBoxPandora"))
        };
    }
}